### ISSUE TITLE
Please help me with the configuration

### ISSUE THREAD

**Issue by flaakesk8** [mattsaxon/HASS-Jablotron80#27]
HI,  please help me.

I've a fresh installation of Homeassistant in a VM on my Synology. Connected to the syno I've Jablotron Alarms JA-82T PC Interface (when I'm using it with WindowsVM and Olinks Software it works like a charm). My Jablotron is an Oasis 80.

![Screenshot 2020-12-10 at 01 15 20](https://user-images.githubusercontent.com/25496035/101704550-4eadb380-3a85-11eb-8778-1b2261d40288.png)

I've also copied the custom_configuration files into /config folder.

my current configuration look like this.

```
alarm_control_panel:
  - platform: Jablotron80
    serial_port: /dev/hidraw1
    code: !secret jablo_pwd
    code_panel_arm_required: False
    code_panel_disarm_required: True
    code_arm_required: False
    code_disarm_required: False
    sensor_names:
      1: "Front Door"
      2: "Garden Door"
      3: "Bedroom"

```

but I only see the control panel in lovelace without any function, also no new sensors are detected.

I've tried different serial_ports but without any success.

![Screenshot 2020-12-10 at 01 11 40](https://user-images.githubusercontent.com/25496035/101704328-c92a0380-3a84-11eb-8e08-c97fd2f52263.png)
![Screenshot 2020-12-10 at 01 13 00](https://user-images.githubusercontent.com/25496035/101704389-f4145780-3a84-11eb-9c24-3133f5e4a4c2.png)

I've also tried the whole setup on a Raspberry Pi, but restarting HA was very slow and sometimes it completely crashed for a long time.

please tell me what I have wrong in my configuration  - 
thanks a lot
Joey
