### ISSUE TITLE
arm night missing in HA alarm card

### ISSUE THREAD

**Issue by Thoky81** [mattsaxon/HASS-Jablotron80#7]
Hi,
I have a question about the alarm arming button. Right now I have in HA only ARM HOME and ARM AWAY. I am also exposing the alarm in Homekit from HA and there I can see also the ARM NIGHT option. All three ARMING states lock my alarm differently and how they should - btw it so far works flawlessly so big thanks to you 😀 But I would like to ask you how can I add the ARM NIGHT in HA alarm control panel too or perhaps change the ARM HOME to ARM NIGHT button. Thanks a lot

**Comment by mattsaxon** [comment]
The HA alarm panel doesn't directly support ARM NIGHT, so I have the following script to achieve this

```
nightalarm:
  alias: Arm Night
  sequence:
    - service: alarm_control_panel.alarm_arm_night
      data:
        entity_id: alarm_control_panel.jablotron_alarm
```

I then have this in the same group as the 'real' control panel so it appears in the UI together.
